# CZ1104 Linear Algebra for Computing - Lab 3

## Name: Chai Wen Xuan

## Mat Number: U2020350F

In [1]:
import numpy as np

### 1) Turning 4by4 matrix into row echelon form in GF(2).

In [2]:
# rowlist = [[0,1,1,1,1],[0,0,0,1,1],[1,1,1,1,1],[0,0,0,0,1],[0,0,0,1,1]]
rowlist = [[0,0,1,1],[1,0,1,1],[1,0,0,1],[1,1,1,1]]

new_rowlist = []
rows_left = set(range(len(rowlist)))


for c in range(len(rowlist[0])):
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        for r in rows_with_nonzero[1:]:
            for x in range(c,len(rowlist[0])):
                rowlist[r][x] += rowlist[pivot][x]
                rowlist[r][x] %= 2
                
new_rowlist = np.array(new_rowlist)

In [3]:
print(new_rowlist)

[[1 0 1 1]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 0 1]]


### 2) Turning 5by5 matrix into row echelon form in general number.

In [4]:
# rowlist = [[0,2,3,4,5],[0,0,0,3,2],[1,2,3,4,5],[0,0,0,6,7],[0,0,0,9,8]]
rowlist = [[8,5,3,1,5],[5,0,9,3,2],[1,0,3,4,5],[0,7,0,3,5],[0,2,0,4,6]]

new_rowlist = []
rows_left = set(range(len(rowlist)))


for c in range(len(rowlist[0])):
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c] !=0]
    if rows_with_nonzero != []:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)
        for r in rows_with_nonzero[1:]:
            multiplier = rowlist[r][c]/rowlist[pivot][c]
            for x in range(c,len(rowlist[0])):
                rowlist[r][x] -= multiplier*rowlist[pivot][x]
        
new_rowlist = np.array(new_rowlist)
for c in range(len(new_rowlist)):
    temp = new_rowlist[c][c]
    for x in range(len(new_rowlist)):
        new_rowlist[c][x] = new_rowlist[c][x]/temp
        if (abs(new_rowlist[c][x])<0.00000000001):
            new_rowlist[c][x] = 0

In [90]:
print(new_rowlist)

[[ 1.          0.625       0.375       0.125       0.625     ]
 [ 0.          1.         -2.28       -0.76        0.36      ]
 [ 0.          0.          1.          2.83333333  3.83333333]
 [ 0.          0.          0.          1.          1.59078591]
 [ 0.          0.          0.          0.          1.        ]]
